version: 2
updates:
  - package-ecosystem: github-actions
    # Using explicit directories instead of glob ("/**") due to
    # [globstar with github-actions ecosystem creates duplicate PRs](https://github.com/dependabot/dependabot-core/issues/10884).
    directories:
      - "/"
      - "/templates/basic"
      - "/templates/github-action"
      - "/templates/typescript"
    open-pull-requests-limit: 20
    labels:
      - "Type: CI"
      - "Type: Dependencies"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directories:
      - "**/*"
    open-pull-requests-limit: 20
    labels:
      - "Type: Dependencies"
    schedule:
      interval: weekly
    groups:
      types:
        patterns:
          - "@types/*"
        exclude-patterns:
          - "@types/node"
      eslint:
        patterns:
          - "*eslint*"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
