name: Setup Nix
description: Install Nix and configure caches

inputs:
  cachix-auth-token:
    description: Cachix authentication token
    required: false
    default: ""
  cachix-name:
    description: Cachix cache name
    required: false
    default: ncaq

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31
      with:
        # セルフホストランナーでうっかり外部からの悪意あるPRを実行許可してしまい、
        # flake.nixの設定を受け入れると好きなキャッシュを入れられたりしてセキュリティリスクがあるため、
        # GitHubホストランナーでのみflake.nixの設定を自動で受け入れるようにしています。
        extra_nix_config: ${{ runner.environment == 'github-hosted' && 'accept-flake-config = true' || '' }}

    - name: Setup Cachix cache
      if: inputs.cachix-auth-token != '' && inputs.cachix-name != ''
      uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
      with:
        name: "${{ inputs.cachix-name }}"
        authToken: "${{ inputs.cachix-auth-token }}"
